version: 1.2
workflows:
   - name: "village-sceQTL"
     subclass: WDL
     primaryDescriptorPath: /scEQTL_wdl.wdl
     testParameterFiles:
     - /test_params/sceqtl_inputs.json
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/

   - name: "QTL-mapping"
     subclass: WDL
     primaryDescriptorPath: /workflows/pipeline_pt2.wdl
     filters: 
        branches: 
          - dev
        tags: 
          - /.*/