version: 1.2
workflows:
   - name: "village-sceQTL"
     subclass: WDL
     primaryDescriptorPath: /scEQTL_wdl.wdl
     testParameterFiles:
     - /test_params/sceqtl_inputs.json
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/

   - name: "QTL-mapping"
     subclass: WDL
     primaryDescriptorPath: /pipeline_pt2.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/

   - name: "subwf-make-qc-plots"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-make-qc-plots.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/

   - name: "subwf-filter-cells-donors"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-filter-cells-donors.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/

   - name: "subwf-run-peer"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-run-peer.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/

   - name: "subwf-qtl-map-each-peer"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-qtl-map-each-peer.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/

   - name: "subwf-qtl-map-nominal"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-qtl-map-nominal.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/

   - name: "test-peer-selection"
     subclass: WDL
     primaryDescriptorPath: /tasks/peer_selection.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/

   - name: "test-cbc-modify"
     subclass: WDL
     primaryDescriptorPath: /tasks/cbc_modify.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/